### ISSUE TITLE
PPT: Add Successes & Challenges

### ISSUE THREAD

**Issue by mewing0328** [smithm4949/PlayDate#10]
Part of the PPT requirement is Successes and Challenges - our current slide has placeholder text.

Please comment your successes and challenges. I will add them all to PPT.

Running List: 
1. **Cloudinary** 
- challenges: new technology, etc.
- successes: deployed, etc.

2. **Model** 
- challenges: to be added
- successes: to be added

3. **View** 
- challenges: CRUD for Events, Dogs, and Comments, etc.
- successes: to be added

4. **Controller**
- challenges: to be added by Myles
- successes: to be added by Myles

**Comment by leeclaire156** [comment]
1. Cloudinary

- Challenges:

Getting back the upload information and manipulating it to the MySQL database to the respective user/dog/event 
Knowing my limitations as a developer and when to reply on my teammates.

- Successes:

Ability to change owner/event/dog profile picture



2. Model

- Challenges: 

Needing to adjust the models from time to time with the proper validations and constraints


3. View
- Challenges: 

Needing to dynamically change information based on what was passed back (**ex: age of dogs less than 1 year old vs older**)


- Success: 

Adding custom helpers for formatting

**Comment by smithm4949** [comment]
Controller:
Challenges - making code modular and resuable in different contexts. Namely, the similar logic used for API and View methods (like Model.findOne) but different results (res.json vs res.render)

Success: Creating my own Promises to wrap methods that use resolve() reject() to send data. This allowed me to make a helper method that gets Promises methods from controllers and can still do after effects on the data if needed when responding to a route request.
