### ISSUE TITLE
Event Detail Page

### ISSUE THREAD

**Issue by mewing0328** [smithm4949/PlayDate#13]
1. Add {{#if ownsXyz}} for edit event button - DONE
2. Add {{#if ownsXyz}} for delete event button - DONE

4. Add {{#if ownsXyz}} for edit COMMENT button 
5. Add {{#if ownsXyz}} for delete COMMENT button 
6. Add a show more button for COMMENTS

**Comment by leeclaire156** [comment]
Waiting on miles to help with edit and delete button showings for everyone regardless of ownership. 
#5 is a like to have.

**Comment by mewing0328** [comment]
Saving these to dos elsewhere so we can focus on the major issues
