### ISSUE TITLE
My Events Page

### ISSUE THREAD

**Issue by mewing0328** [smithm4949/PlayDate#15]
1. Activate that Add Event button so a form can populate there on that page and the user can make an event on that page without going to the My Profile page.

**Comment by smithm4949** [comment]
@mewing0328 not sure if you've already tackled this one BUT you should be able to reuse the code for the other events page just under a different URL.

Meaning, if you copy the get /profile/events/:id logic in the viewRoutes folder and just make another method that does the same thing and renders the same handlebar just under a different URL (/event/:id) that should make it easy on you!

**Comment by leeclaire156** [comment]
Decided to delete the Add Event button on the My Events page and leave adding events to the profile page.
