### ISSUE TITLE
Urgent: View Other User's Profile

### ISSUE THREAD

**Issue by mewing0328** [smithm4949/PlayDate#19]
**We need users to be able to see the other user's profiles & that person's dog(s).**

Back end: 
- need a backend that gets single owner + include dog model based on id that passes through to render new handlebars profilesingle.handlebar
- the url would be localhost:3009/profile/{:id} (which is different from the logged in user's editing page which is /profile/owners/{:id}

Front end: another profile handlebar to show the profile card and dog card stacked on top

**Comment by leeclaire156** [comment]
Finished front end (profilesingle handlebars)

**Comment by leeclaire156** [comment]
Finished back end. Users can now be view via the comment section and the users can be viewed under Host section of their respective event card(s).
