### ISSUE TITLE
*Urgent: Comment Edit/Delete Selectivity

### ISSUE THREAD

**Issue by mewing0328** [smithm4949/PlayDate#20]
Events have comments, comments should be tied to the user who wrote the comment BUT when I try to use a {{if ownsComment}} in handlebars, the delete button and edit button are not showing.

Huddle so MaSandra can explain 

Also, on my local version, I had to add id to comment attributes for eventController.js because data-id in the front end wasn't understanding {{comment.id}}

![image](https://user-images.githubusercontent.com/109485265/223003004-a29a0cd7-a8fb-458b-8598-ae247fb1192f.png)

**Comment by mewing0328** [comment]
@mewing0328 For myself - test Delete and Edit comment after Myles edits back end

**Comment by leeclaire156** [comment]
@smithm4949

**Comment by mewing0328** [comment]
@smithm4949  Can you do this also but for {{if ownsComment}}?

![image](https://user-images.githubusercontent.com/109485265/223125574-2a5c9543-3320-478d-bf75-d4db91759641.png)

**Comment by smithm4949** [comment]
Fixed with PR #30

**Comment by mewing0328** [comment]
Can you do the same for {{ if ownsDog }}? We'll add the function to the profile single so I don't see edit and delete for someone else's dog?

**Comment by smithm4949** [comment]
Done, fix is in PR
