### ISSUE TITLE
Rendering of Events for Home and My Events

### ISSUE THREAD

**Issue by mewing0328** [smithm4949/PlayDate#3]
![image](https://user-images.githubusercontent.com/109485265/222968903-0d48e6f0-543f-426c-89fb-4b8c5354fadc.png)
![image](https://user-images.githubusercontent.com/109485265/222968929-09515ad1-0033-46dc-84a8-0956cf249ce0.png)

**Comment by leeclaire156** [comment]
@smithm4949 This issue is mostly resolved except for @VenBak 's part for the `Local Event`
